base_url = "https://lumic.cc"
title = "Lumic Control Center"
description = "Lumic Control Center is host-native Linux server, application and infrastructure management with CLI, UI and MCP."
default_language = "en"
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = false

[markdown]
smart_punctuation = true

[extra]
github = "https://github.com/bpstr/lumic"
version = "v2 pre-alpha"
