[package]
name = "lumic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "lumic"
path = "src/main.rs"

[dependencies]
clap.workspace = true
lumic-core = { path = "../lumic-core" }
lumic-platform = { path = "../lumic-platform" }
serde_json.workspace = true
tokio.workspace = true
