name: Lumic Deployment

on: [push]
jobs:
  test-curl-action:
    name: "Deploy to Lumic"
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Lumic webhook"
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.lumic_webhook_url }}
          method: "POST"
          accept: 202
          timeout: 1000
          basic-auth-token: ${{ secrets.lumic_auth_token }}
          retries: 2
